# Generated by Django 3.1.7 on 2021-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='o_review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
