# Generated by Django 3.1.7 on 2021-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_auto_20210329_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='o_review',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pbattery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='q_rating',
            field=models.IntegerField(default=0),
        ),
    ]
